#!/usr/bin/env node
/**
 * ollama-start.js
 * Start Ollama container with proper model, for use by NimbusHelmAI or standalone.
 * Cross-platform: Linux, macOS, Windows (no WSL required)
 *
 * Author: Amit Perelman
 * Date: April 9, 2026
 *
 * Usage:
 *   node ollama-start.js [--config config.json] [--model model:tag]
 *
 * Config JSON (optional, generated by Nimbus UI):
 * {
 *   "model":      "qwen2.5-coder:7b",
 *   "port":       11434,
 *   "keepAlive":  "30m",
 *   "gpuMode":    "auto"        // "auto" | "force" | "cpu"
 * }
 *
 * --model overrides both config file and default model.
 */

'use strict';

const { execSync, spawnSync } = require('child_process');
const fs   = require('fs');
const path = require('path');
const os   = require('os');

// ─── Config defaults ──────────────────────────────────────────────────────────
const DEFAULTS = {
  model:     'qwen2.5-coder:7b',
  port:      11434,
  keepAlive: '30m',
  gpuMode:   'auto',   // 'auto' | 'force' | 'cpu'
};

// ─── ANSI colors (disabled on Windows unless WT/ConEmu detected) ──────────────
const isColorSupported =
  process.platform !== 'win32' ||
  process.env.WT_SESSION ||
  process.env.TERM_PROGRAM === 'vscode';

const c = {
  green:  isColorSupported ? '\x1b[32m' : '',
  red:    isColorSupported ? '\x1b[31m' : '',
  yellow: isColorSupported ? '\x1b[33m' : '',
  reset:  isColorSupported ? '\x1b[0m'  : '',
};

const ok   = (msg) => console.log(`${c.green}✅ ${msg}${c.reset}`);
const err  = (msg) => console.log(`${c.red}❌ ${msg}${c.reset}`);
const warn = (msg) => console.log(`${c.yellow}⚠️  ${msg}${c.reset}`);

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Run a shell command, return { ok, output }. Never throws. */
function run(cmd, opts = {}) {
  try {
    const out = execSync(cmd, { encoding: 'utf8', stdio: 'pipe', ...opts });
    return { ok: true, output: out.trim() };
  } catch (e) {
    return { ok: false, output: (e.stdout || '') + (e.stderr || '') };
  }
}

/** Run a command, stream its stdout/stderr to our console. Returns exit code. */
function runLive(cmd) {
  const result = spawnSync(
    process.platform === 'win32' ? 'cmd' : 'sh',
    process.platform === 'win32' ? ['/c', cmd] : ['-c', cmd],
    { stdio: 'inherit', encoding: 'utf8' }
  );
  return result.status ?? 1;
}

/** Sleep for ms milliseconds */
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// ─── Docker auto-start ────────────────────────────────────────────────────────

/** Try to ensure Docker is running. Returns true if successful. */
function ensureDockerRunning() {
  // First check if Docker is already running
  const check = run('docker info');
  if (check.ok) return true;

  warn('Docker is not running. Attempting to start...');

  // Check if we have sudo access
  const sudoCheck = run('which sudo');

  // Try systemctl (Linux with systemd)
  const systemctlCheck = run('which systemctl');
  if (systemctlCheck.ok) {
    const cmd = sudoCheck.ok
      ? 'sudo systemctl start docker'
      : 'systemctl start docker';
    ok('Starting Docker via systemctl...');
    const start = run(cmd);
    if (start.ok) {
      ok('Docker started via systemctl');
      return waitForDocker();
    }
    warn(`systemctl failed: ${start.output}`);
  }

  // Try service (older Linux, some macOS)
  const serviceCheck = run('which service');
  if (serviceCheck.ok) {
    const cmd = sudoCheck.ok
      ? 'sudo service docker start'
      : 'service docker start';
    ok('Starting Docker via service...');
    const start = run(cmd);
    if (start.ok) {
      ok('Docker started via service');
      return waitForDocker();
    }
    warn(`service failed: ${start.output}`);
  }

  // Windows: try starting Docker Desktop
  if (process.platform === 'win32') {
    warn('Please start Docker Desktop manually.');
    return false;
  }

  // macOS: try open Docker.app
  if (process.platform === 'darwin') {
    const start = run('open -a Docker');
    if (start.ok) {
      ok('Starting Docker Desktop...');
      return waitForDocker(15000); // Docker Desktop takes longer
    }
  }

  err('Could not start Docker automatically. Please start it manually.');
  return false;
}

/** Wait for Docker to become ready. Returns true if ready within timeout. */
function waitForDocker(timeoutMs = 10000) {
  const start = Date.now();
  ok('Waiting for Docker to be ready...');

  while (Date.now() - start < timeoutMs) {
    const check = run('docker info');
    if (check.ok) {
      ok('Docker is ready');
      return true;
    }
    // Brief pause between checks
    const waitUntil = Date.now() + 1000;
    while (Date.now() < waitUntil) {
      // busy-wait is fine for a short duration in a startup script
    }
  }

  err('Docker did not become ready in time. Please check manually.');
  return false;
}

// ─── GPU detection ────────────────────────────────────────────────────────────

function hasNvidiaGpu() {
  if (process.platform === 'win32') {
    // On Windows use nvidia-smi.exe
    const r = run('nvidia-smi --query-gpu=name --format=csv,noheader');
    return r.ok && r.output.length > 0;
  }
  // Linux / macOS
  const r = run('nvidia-smi');
  return r.ok;
}

// ─── Load config ──────────────────────────────────────────────────────────────

function loadConfig() {
  const args = process.argv.slice(2);

  // Check for --config
  const cfgIdx = args.indexOf('--config');
  let fileConfig = {};
  if (cfgIdx !== -1 && args[cfgIdx + 1]) {
    const cfgPath = path.resolve(args[cfgIdx + 1]);
    if (!fs.existsSync(cfgPath)) {
      err(`Config file not found: ${cfgPath}`);
      process.exit(1);
    }
    try {
      fileConfig = JSON.parse(fs.readFileSync(cfgPath, 'utf8'));
    } catch (e) {
      err(`Failed to parse config: ${e.message}`);
      process.exit(1);
    }
  }

  // Check for --model (overrides everything)
  const modelIdx = args.indexOf('--model');
  let cliModel = null;
  if (modelIdx !== -1 && args[modelIdx + 1]) {
    cliModel = args[modelIdx + 1];
  }

  const merged = { ...DEFAULTS, ...fileConfig };
  if (cliModel) {
    merged.model = cliModel;
  }

  return merged;
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const cfg = loadConfig();

  console.log('');
  ok(`Setting up Ollama with ${cfg.model}...`);
  console.log(`  Platform : ${os.platform()} (${os.arch()})`);
  console.log(`  Port     : ${cfg.port}`);
  console.log(`  Model    : ${cfg.model}`);
  console.log(`  GPU mode : ${cfg.gpuMode}`);

  // ── Check / start Docker ────────────────────────────────────────────────────
  if (!ensureDockerRunning()) {
    err('Docker is required to run Ollama. Exiting.');
    process.exit(1);
  }

  // ── Remove existing container ───────────────────────────────────────────────
  const existing = run('docker ps -a --format "{{.Names}}"');
  if (existing.output.split('\n').some((n) => n.trim() === 'ollama')) {
    warn('Removing existing Ollama container...');
    run('docker rm -f ollama');
  }

  // ── Decide GPU mode ─────────────────────────────────────────────────────────
  let useGpu = false;
  if (cfg.gpuMode === 'force') {
    useGpu = true;
  } else if (cfg.gpuMode === 'cpu') {
    useGpu = false;
  } else {
    // auto
    useGpu = hasNvidiaGpu();
  }

  const keepAlive = useGpu ? cfg.keepAlive : '15m';  // shorter keep-alive in CPU mode

  // ── Build docker run command ────────────────────────────────────────────────
  const gpuFlags = useGpu
    ? ['--gpus all', '-e GGML_CUDA_ENABLE_UNIFIED_MEMORY=1']
    : [];

  const dockerCmdParts = [
    'docker run -d',
    '--name ollama',
    `-p ${cfg.port}:11434`,
    '-v ollama:/root/.ollama',
    `-e OLLAMA_HOST=0.0.0.0`,
    `-e OLLAMA_KEEP_ALIVE=${keepAlive}`,
  ];

  if (useGpu) {
    dockerCmdParts.push('--gpus all');
    dockerCmdParts.push(...gpuFlags);
  }

  dockerCmdParts.push('ollama/ollama:latest');

  const dockerCmd = dockerCmdParts
    .filter(Boolean)
    .join(' ');

  ok(`Starting Ollama container (${useGpu ? 'GPU' : 'CPU'} mode)...`);
  const startResult = runLive(dockerCmd);
  if (startResult !== 0) {
    err('Failed to start Ollama container. Check Docker is running.');
    process.exit(1);
  }

  if (useGpu) {
    ok('Ollama started with GPU acceleration');
  } else {
    warn('Ollama running in CPU mode (no GPU detected)');
  }

  // ── Wait for Ollama to be ready ─────────────────────────────────────────────
  console.log('');
  ok('Waiting for Ollama to be ready...');
  await sleep(5000);

  // ── Pull model ──────────────────────────────────────────────────────────────
  ok(`Pulling ${cfg.model} model (this may take a while)...`);
  console.log('⏳ Downloading model...');

  const pullResult = runLive(`docker exec ollama ollama pull ${cfg.model}`);
  if (pullResult === 0) {
    ok('Model downloaded successfully');
  } else {
    err('Failed to download model. Check Docker logs: docker logs ollama');
  }

  // ── Verify ──────────────────────────────────────────────────────────────────
  console.log('');
  ok('Verifying Ollama...');
  runLive('docker exec ollama ollama list');

  // ── API check ───────────────────────────────────────────────────────────────
  const http = require('http');
  await new Promise((resolve) => {
    const req = http.get(`http://localhost:${cfg.port}/api/tags`, (res) => {
      ok(`Ollama API is accessible at http://localhost:${cfg.port}`);
      resolve();
    });
    req.on('error', () => {
      warn('Ollama API not responding yet. It may still be starting.');
      resolve();
    });
    req.setTimeout(3000, () => {
      req.destroy();
      warn('Ollama API check timed out. It may still be starting.');
      resolve();
    });
  });

  console.log('');
  ok('Done! Ollama is running.');
}

main().catch((e) => {
  err(`Unexpected error: ${e.message}`);
  process.exit(1);
});